name: aventura_com_bako
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^3.2.8
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  flutter_screenutil: ^5.3.1
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  google_sign_in: ^5.2.4
  graphql_flutter: ^5.0.1
  image_picker: ^0.8.4+11
  flame: ^1.1.0
  flame_tiled: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  mocktail: ^0.3.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "assets/bako_vetor.png"
  image_path_android: "assets/bako_vetor.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Light.ttf
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tiles/
    - assets/images/SERENE_VILLAGE_REVAMPED/
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
