name: aventura_com_bako
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  basic_utils: ^5.3.0
  carousel_slider: ^4.1.1
  cloud_functions: ^4.0.11
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  eca_packages:
    # path: ../../eca_packages/
    git:
      url: https://github.com/evertonfoz/eca_packages.git
  equatable: ^2.0.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.0
  flame: ^1.2.1
  flame_tiled: ^1.6.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.2
  flutter_mobx: ^2.0.6+5
  get: ^4.6.5
  google_sign_in: ^6.0.2
  graphql_flutter: ^5.1.0
  image_picker: ^0.8.5+3
  mobile_scanner: ^3.0.0
  status_bar_control: ^3.2.1
  timelines: ^0.1.0
  flip_card: ^0.7.0
  word_search_safety: ^0.1.2-nullsafety.1


dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  mocktail: ^0.3.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "assets/bako_vetor.png"
  image_path_android: "assets/bako_vetor.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Light.ttf
    - family: Letters_for_leaners
      fonts:
        - asset: fonts/Letters_for_Learners.ttf
          
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tiles/
    - assets/audio/
  uses-material-design: true

  # flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#1B9D2C"
  #  background_image: "assets/images/brand/brand_1407x295.png"
  image: "assets/images/launch_screen.png"
  fullscreen: true
  web: false
