name: aventura_com_bako
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_functions: ^3.3.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  eca_packages:
    path: ../eca_packages/
  firebase_auth: ^3.4.2
  flutter:
    sdk: flutter
  firebase_core: ^1.19.2
  flutter_screenutil: ^5.5.3+2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  get: ^4.6.5
  google_sign_in: ^5.4.0
  graphql_flutter: ^5.1.0
  image_picker: ^0.8.5+3
  flame: ^1.2.1
  flame_tiled: ^1.6.0
  qr_code_scanner: ^1.0.0
  basic_utils: ^4.4.1
  carousel_slider: ^4.1.1
  timelines: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  mocktail: ^0.3.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "assets/bako_vetor.png"
  image_path_android: "assets/bako_vetor.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-Light.ttf
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/tiles/
  uses-material-design: true

  # flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#1B9D2C"
  #  background_image: "assets/images/brand/brand_1407x295.png"
  image: "assets/images/launch_screen.png"
  fullscreen: true
  web: false